from rich.console import Console
from rich.table import Table


def print_help() -> None:
    console: Console = Console()

    table: Table = Table(
        border_style="green",
        show_header=True,
        header_style="bold cyan",
        box=None,
        show_lines=False,
    )
    options: list[str] = [
        "-h, --help, -H -? --?",
        "-nc, --no_cookie, --nocookie, --no-cookie",
        "-cm, --community",
        "--join 'COMMUNITY_NAME'",
        "--leave 'COMMUNITY_NAME'",
        "",
        "-g 'ive', --group 7",
        "<If not specified, all items except CMT(comment) will be selected by default>",
        "-b, --board",
        "-c, --cmt",
        "-l, --live, --live-only",
        "-m, --media, --media-only",
        "-p, --photo, --photo-only",
        "-n, --notice, --notice-only",
        "-fc, --fanclub-only, --fanclub",
        "-nfc, --no-fanclub",
        "",
        "--T --t <datetime start>",
        "--TT --tt <datetime end>",
        "",
        "--signup",
        "--change-password --changepassword",
        "",
        "-q, --quality",
        "-v, --vcodec",
        "-na, -an, --no-audio --skip-audio --skip-a --skipaudio",
        "-nv, -vn, --no-video, --skip-videos, --skip-v, --skip-video --skipvideo",
        "--ss",
        "--to",
        "",
        "--list",
        "--del-after-done",
        "--skip-merge",
        "--skip-mux",
        "-k, --key, --keys",
        "--skip-dl, --skip-download",
        "--skip-json, --skip-Json, --skip-JSON --skipjson",
        "--skip-thumbnails, --skip-thb --skipthumbnails",
        "--skip-images, --skip-imgs, --skip-image, --skip-img --skipimage",
        "--skip-playlist, --skip-Playlist, --skip-pl --skipplaylist",
        "--skip-html, --skip-Html, --skip-HTML --skiphtml",
        "--no-info, --noinfo",
        "--nosubfolder, --no-subfolder, --no_subfolder",
        "--retitle",
        "--artisid",
        "--cdm",
        "--cache",
        "--no-cache",
        "--save-dir",
        "",
        "-S, --subs-only",
        "-ns, --no-subs",
        "--keep-subs, --keepsubs",
        "",
        "--cookies",
        "",
        "--version, --v",
    ]

    descriptions: list[str] = [
        "show this help message and exit",
        "do not use cookies",
        "list all current communities in Berriz",
        "join a community",
        "leave a community",
        "",
        "which artist's community ('ive' or '7') | only allow one community each",
        "",
        "select board content",
        "select comment content",
        "select live content",
        "select media section video content",
        "select media section photo content",
        "select notice section content",
        "show fanclub-only content",
        "show non-fanclub content",
        "",
        "filter content by start date/time (ISO8601, %Y%M%D, YYMMDD, %M%S, 19700101 0000) [KST Time only], Don't use 25 use 2025",
        "[Optional] filter content by end date/time (ISO8601, %Y%M%D, YYMMDD, %M%S, 19700101 0000) [KST Time only], Don't use 25 use 2025",
        "",
        "Berriz account registration",
        "change current account password",
        "",
        "choese video quality (1080p, 720p, 480p, 360p, 240p, 144p, ask, None)",
        "video codec | H264",
        "do not download audio tracks",
        "do not download video tracks",
        "Specify the video start time",
        "Specify the video end time",
        "",
        "skip downloading and list available tracks",
        "delete after completion (true/false)",
        "skip merge after completion",
        "skip mux after merge",
        "show key and skip download",
        "skip all downloads",
        "skip saving JSON locally",
        "skip saving thumbnails locally",
        "skip saving images locally",
        "skip saving playlist locally",
        "skip saving HTML format locally",
        "no [JSON / HTML / m3u8 / MPD / thumbnails]",
        "no extra subfolders for each content",
        "filter titles using regular expressions",
        "specify ArtistID | --artisid 71,72,73 | --artisid 71 Only work in (0. Artis archive)",
        "override the CDM that will be used for decryption",
        "disable the use of the CDM and only retrieve decryption keys from Key Vaults",
        "disable the use of Key Vaults and retrieve decryption keys only from CDM",
        "Set output directory",
        "",
        "Only download subtitle tracks",
        "Do not download subtitle tracks",
        "When subtitle mux to MKV, keep sub file after done (default: false)",
        "",
        "User specified cookie file path",
        "",
        "Show version",
    ]

    for option, description in zip(options, descriptions):
        if option == "" and description == "":
            table.add_row("", "", end_section=True)
        else:
            table.add_row(option, description)
    console.print(table)
